# Generated by Django 4.2.29 on 2026-03-30 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'db_table': 'cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_days_from', models.PositiveIntegerField(verbose_name='Срок от (дней)')),
                ('delivery_days_to', models.PositiveIntegerField(verbose_name='Срок до (дней)')),
                ('calculation_type', models.CharField(choices=[('weight', 'По весу'), ('volume', 'По объёму'), ('max_value', 'По наибольшему значению'), ('mixed', 'Смешанный')], default='weight', max_length=20, verbose_name='Тип расчёта')),
                ('currency', models.CharField(default='USD', max_length=10, verbose_name='Валюта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes_from', to='calculator.city', verbose_name='Город отправки')),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes_to', to='calculator.city', verbose_name='Город доставки')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
                'db_table': 'routes',
                'unique_together': {('from_city', 'to_city')},
            },
        ),
        migrations.CreateModel(
            name='RouteTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Мин. вес (кг)')),
                ('max_weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Макс. вес (кг)')),
                ('min_volume', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Мин. объём (м³)')),
                ('max_volume', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Макс. объём (м³)')),
                ('price_per_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Тариф за кг')),
                ('price_per_m3', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Тариф за м³')),
                ('margin_type', models.CharField(choices=[('fixed', 'Фиксированная'), ('percentage', 'Процент')], default='fixed', max_length=20, verbose_name='Тип маржи')),
                ('margin_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Значение маржи')),
                ('fixed_surcharge', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Фикс. надбавка')),
                ('minimum_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Мин. стоимость')),
                ('weight_coefficient', models.DecimalField(decimal_places=4, default=1, max_digits=10, verbose_name='Коэфф. веса')),
                ('volume_coefficient', models.DecimalField(decimal_places=4, default=1, max_digits=10, verbose_name='Коэфф. объёма')),
                ('priority', models.IntegerField(default=0, verbose_name='Приоритет')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='calculator.route', verbose_name='Маршрут')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'db_table': 'route_tariffs',
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=100, verbose_name='Тип сущности')),
                ('entity_id', models.PositiveIntegerField(verbose_name='ID сущности')),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Изменение'), ('delete', 'Удаление')], max_length=20, verbose_name='Действие')),
                ('old_value', models.JSONField(blank=True, null=True, verbose_name='Старое значение')),
                ('new_value', models.JSONField(blank=True, null=True, verbose_name='Новое значение')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кем изменено')),
            ],
            options={
                'verbose_name': 'Запись журнала',
                'verbose_name_plural': 'Журнал изменений',
                'db_table': 'audit_log',
                'ordering': ['-changed_at'],
            },
        ),
    ]
